
SET DEBUG=0
SET INFO=1
SET WARN=2
SET ERROR=3

SET INIFILE=pinstall.ini

SET DIRBASE=InstallPack\
SET INSTALL_DIR=%DIRBASE%Installers\
SET DOF_CONFIG_DIR=%DIRBASE%DOFConfig\
SET DOF_CONFIG_ARCHIVE=%DOF_CONFIG_DIR%directoutputconfig.zip
SET DOF_CONFIG_CABINET=%DOF_CONFIG_DIR%cabinet.xml
SET DOF_CONFIG_GLOBALB2S_CONFIG=%DOF_CONFIG_DIR%GlobalConfig_B2SServer.xml
SET TEMP_DIR=Temp\

SET INSTALLBASE_LOC=C:\

REM VPX Installation locations
SET INSTALL_VPX_LOC=%INSTALLBASE_LOC%Visual Pinball\
SET INSTALL_VPX_TABLES_LOC=%install_vpx_loc%Tables\
SET INSTALL_VPX_MAME_LOC=%install_vpx_loc%VPinMAME\
SET VPX_UNINSTALL=%INSTALL_VPX_LOC%uninstall.exe

REM VPX Installation locations
SET INSTALL_DOF_LOC=%INSTALLBASE_LOC%DirectOutput\

SET INSTALL_PINUP_LOC=%INSTALLBASE_LOC%PinUpSystem\
SET INSTALL_PINUP_PUPVIDEOS_LOC=%INSTALL_PINUP_LOC%PUPVideos\
